// features/farm-game/styles.ts
import { Platform, StyleSheet } from "react-native";

import { SCREEN_W } from "./constants";

export const FF = "FredokaOne_400Regular";

export const P = {
  green1: "#14532D",
  green2: "#22C55E",
  green3: "#DCFCE7",
  greenDeep: "#052E16",
  brown1: "#78350F",
  brown2: "#A16207",
  cream: "#FEF9C3",
  gold: "#F59E0B",
  goldLight: "#FBBF24",
  white: "#FFFFFF",
  gray1: "#F5F5F4",
  ink: "#14532D", // dark text over glass
};

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#87CEEB" },

  // Header (covers the status bar)
  headerWrap: { backgroundColor: P.green1 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingBottom: 6,
  },
  headerLeft: { flexDirection: "row", alignItems: "center", gap: 10 },
  lvlBadge: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: P.greenDeep,
    borderWidth: 2,
    borderColor: P.goldLight,
    alignItems: "center",
    justifyContent: "center",
  },
  lvlNum: {
    fontFamily: FF,
    fontSize: 18,
    color: P.goldLight,
    lineHeight: 20,
  },
  lvlLbl: {
    fontFamily: FF,
    fontSize: 7,
    color: "#86EFAC",
    letterSpacing: 1.5,
  },
  title: {
    fontSize: 21,
    fontFamily: FF,
    color: P.white,
    letterSpacing: 0.5,
  },
  dayPill: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    marginTop: 2,
  },
  dayPillTxt: { fontSize: 10, fontFamily: FF, color: "#BBF7D0" },

  chips: { flexDirection: "row", gap: 6, alignItems: "center" },
  goldChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: P.greenDeep,
    borderWidth: 1,
    borderColor: "rgba(251,191,36,0.55)",
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 20,
  },
  goldIcon: { fontSize: 13 },
  goldTxt: { color: P.goldLight, fontFamily: FF, fontSize: 13 },
  goldPlus: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: P.goldLight,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 1,
  },
  goldPlusTxt: {
    fontFamily: FF,
    fontSize: 11,
    color: P.greenDeep,
    lineHeight: 13,
  },
  readyChip: {
    backgroundColor: P.cream,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: P.goldLight,
  },
  readyChipTxt: { color: P.brown1, fontFamily: FF, fontSize: 12 },

  // XP
  xpWrap: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    paddingBottom: 10,
  },
  xpTrack: {
    height: 9,
    backgroundColor: P.greenDeep,
    borderRadius: 5,
    overflow: "hidden",
  },
  xpFill: {
    height: "100%",
    backgroundColor: "#4ADE80",
    borderRadius: 5,
    overflow: "hidden",
  },
  xpShine: {
    position: "absolute",
    top: 1,
    left: 4,
    right: 4,
    height: 3,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.35)",
  },
  xpRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 3,
  },
  xpText: { color: "#D1FAE5", fontFamily: FF, fontSize: 10 },
  xpPct: { color: "#86EFAC", fontFamily: FF, fontSize: 10 },

  // Canvas
  canvasWrap: {
    flex: 1,
    backgroundColor: "#87CEEB",
    position: "relative",
  },

  // ── Liquid glass base ──
  glass: {
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.30)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.60)",
  },
  floatShadow: {
    ...Platform.select({
      ios: {
        shadowColor: "#0F3D22",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.22,
        shadowRadius: 12,
      },
      android: {},
    }),
  },

  // Hint chip (glass, top of the scene)
  hintChip: {
    position: "absolute",
    top: 12,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 22,
  },
  hintDot: { width: 8, height: 8, borderRadius: 4 },
  hintTxt: { fontFamily: FF, fontSize: 11, color: P.ink },
  recenterBtn: { position: "absolute", top: 10, right: 12 },
  recenterGlass: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  recenterTxt: { fontSize: 18 },
  buyBtn: {
    minWidth: 64,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 13,
    backgroundColor: P.gold,
    alignItems: "center",
    justifyContent: "center",
  },
  buyBtnTxt: { fontFamily: FF, fontSize: 12, color: "#5A3A00" },
  buyBtnOwned: { backgroundColor: "rgba(76,175,80,0.18)" },
  buyBtnOwnedTxt: { fontFamily: FF, fontSize: 12, color: "#2E7D32" },
  buyBtnLocked: { backgroundColor: "rgba(156,163,175,0.22)" },
  buyBtnLockedTxt: { fontFamily: FF, fontSize: 13, color: "#6B7280" },

  // Level up banner
  lvlUpBanner: {
    position: "absolute",
    top: "30%",
    alignSelf: "center",
    backgroundColor: "rgba(20,83,45,0.92)",
    borderWidth: 2,
    borderColor: P.goldLight,
    borderRadius: 18,
    paddingHorizontal: 26,
    paddingVertical: 14,
    alignItems: "center",
    gap: 2,
  },
  lvlUpStar: { fontSize: 30 },
  lvlUpTxt: {
    fontFamily: FF,
    fontSize: 20,
    color: P.goldLight,
    letterSpacing: 1,
  },

  // ── Floating footer ──
  floatFooter: {
    position: "absolute",
    left: 14,
    right: 14,
    gap: 10,
  },
  fabRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fab: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  fabEm: { fontSize: 22 },
  fabLbl: { fontFamily: FF, fontSize: 8, color: P.ink, marginTop: 1 },
  cropChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 26,
  },
  cropChipEm: { fontSize: 21 },
  cropChipTop: { flexDirection: "row", alignItems: "center", gap: 5 },
  cropChipName: { fontSize: 12, fontFamily: FF, color: P.ink },
  cropChipRarity: {
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 6,
  },
  cropChipRarityTxt: { fontSize: 7, fontFamily: FF, color: P.white },
  cropChipCost: { fontSize: 9, fontFamily: FF, color: P.brown2 },
  cropChipPec: { fontSize: 9, fontFamily: FF, color: "#9333EA", marginTop: 1 },

  // Tool dock (glass)
  toolDock: {
    flexDirection: "row",
    gap: 5,
    padding: 6,
    borderRadius: 26,
  },
  toolBtn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 9,
    borderRadius: 20,
    gap: 1,
  },
  toolCount: {
    position: "absolute",
    top: 2,
    right: 6,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.85)",
    zIndex: 2,
  },
  toolCountTxt: { color: P.white, fontFamily: FF, fontSize: 9 },
  toolEm: { fontSize: 20 },
  toolLbl: { fontSize: 9, fontFamily: FF, color: P.ink },
  toolLblActive: { color: P.white },

  // Floating labels
  floatWrap: {
    position: "absolute",
    width: 80,
    alignItems: "center",
  },
  floatText: {
    fontFamily: FF,
    fontSize: 15,
    textShadowColor: "rgba(0,0,0,0.18)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },

  // Shop modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.42)",
    justifyContent: "flex-end",
  },
  shopPanel: {
    backgroundColor: P.white,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    padding: 18,
    paddingBottom: Platform.OS === "ios" ? 36 : 20,
    maxHeight: "88%",
  },
  shopHandle: {
    width: 38,
    height: 4,
    backgroundColor: "#D1D5DB",
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 14,
  },
  shopHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  shopTitle: { fontSize: 19, fontFamily: FF, color: P.green1, marginBottom: 3 },
  shopGold: { fontSize: 13, fontFamily: FF, color: P.brown2 },
  getCoinsBtn: {
    backgroundColor: P.gold,
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 18,
  },
  getCoinsTxt: { fontFamily: FF, fontSize: 12, color: P.white },

  // ── Accordion (shop sections) ──
  accSection: { marginBottom: 8 },
  accHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingVertical: 11,
    paddingHorizontal: 12,
    borderRadius: 13,
    backgroundColor: P.gray1,
    borderWidth: 2,
    borderColor: "transparent",
  },
  accHeaderOpen: {
    backgroundColor: "#EEF2F0",
    borderColor: "rgba(20,83,45,0.10)",
  },
  accChevron: {
    fontFamily: FF,
    fontSize: 13,
    color: "#9CA3AF",
    width: 12,
    textAlign: "center",
  },
  accChevronOpen: { transform: [{ rotate: "90deg" }] },
  accEmoji: { fontSize: 18 },
  accDot: { width: 8, height: 8, borderRadius: 4 },
  accTitle: { fontFamily: FF, fontSize: 13, letterSpacing: 0.3 },
  accRange: { fontFamily: FF, fontSize: 10, color: "#9CA3AF" },
  accCount: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 9,
    backgroundColor: "#E5E7EB",
  },
  accCountLocked: { backgroundColor: "rgba(156,163,175,0.22)" },
  accCountTxt: { fontFamily: FF, fontSize: 9, color: "#4B5563" },
  accBody: { paddingTop: 8 },
  accHint: {
    fontFamily: FF,
    fontSize: 10,
    color: "#9CA3AF",
    marginBottom: 6,
    marginLeft: 2,
  },

  cropRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 11,
    borderRadius: 13,
    backgroundColor: P.gray1,
    marginBottom: 7,
    borderWidth: 2,
    borderColor: "transparent",
  },
  cropRowSel: { borderColor: P.green2, backgroundColor: P.green3 },
  cropRowDim: { opacity: 0.45 },
  mysteryRow: {
    backgroundColor: "#F8FAFC",
    borderStyle: "dashed",
    borderColor: "#CBD5E1",
  },
  mysteryName: { fontSize: 14, fontFamily: FF, color: "#64748B" },
  cropEm: { fontSize: 27 },
  cropNameRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  cropName: { fontSize: 14, fontFamily: FF, color: "#1F2937" },
  cropDet: { fontSize: 11, fontFamily: FF, color: "#6B7280", marginTop: 2 },
  pecLine: { fontSize: 10, fontFamily: FF, color: "#9333EA", marginTop: 2 },
  lvlTag: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 7,
    backgroundColor: "#0EA5E9",
  },
  lvlTagTxt: { fontSize: 8, fontFamily: FF, color: P.white },
  stockBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 7,
  },
  soldOutBadge: { backgroundColor: "#9CA3AF" },
  stockBadgeTxt: { fontSize: 8, fontFamily: FF, color: P.white },
  xpBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 7 },
  xpBadgeTxt: { color: P.white, fontFamily: FF, fontSize: 10 },
  closeBtn: {
    marginTop: 7,
    backgroundColor: "#F3F4F6",
    padding: 13,
    borderRadius: 11,
    alignItems: "center",
  },
  closeBtnTxt: { fontFamily: FF, color: "#374151", fontSize: 13 },

  // Coin market
  marketSub: {
    fontSize: 12,
    fontFamily: FF,
    color: "#6B7280",
    marginTop: 6,
    marginBottom: 12,
  },
  packRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 13,
    borderRadius: 14,
    backgroundColor: P.gray1,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: "transparent",
  },
  packRowHot: {
    borderColor: P.goldLight,
    backgroundColor: "#FFFBEB",
  },
  packRowDim: { opacity: 0.4 },
  storeStatus: {
    fontSize: 11,
    fontFamily: FF,
    color: "#6B7280",
    textAlign: "center",
    marginBottom: 8,
  },
  storeError: {
    fontSize: 11,
    fontFamily: FF,
    color: "#DC2626",
    textAlign: "center",
    marginBottom: 8,
  },
  packTag: {
    position: "absolute",
    top: -8,
    right: 12,
    backgroundColor: P.gold,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    zIndex: 2,
  },
  packTagTxt: {
    fontFamily: FF,
    fontSize: 8,
    color: P.white,
    letterSpacing: 0.5,
  },
  packEm: { fontSize: 28 },
  packCoins: { fontSize: 15, fontFamily: FF, color: "#1F2937" },
  packBonus: { fontSize: 10, fontFamily: FF, color: P.green2, marginTop: 2 },
  packPrice: {
    backgroundColor: P.green2,
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderRadius: 11,
    minWidth: 84,
    alignItems: "center",
  },
  packPriceTxt: { fontFamily: FF, fontSize: 12, color: P.white },
  packPriceBusy: { backgroundColor: "#86EFAC" },
  marketDisclaimer: {
    fontSize: 9,
    fontFamily: FF,
    color: "#9CA3AF",
    textAlign: "center",
    marginTop: 4,
    marginBottom: 6,
  },

  // Day modal
  dayOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    alignItems: "center",
    justifyContent: "center",
  },
  dayCard: {
    backgroundColor: P.white,
    borderRadius: 22,
    padding: 30,
    alignItems: "center",
    width: SCREEN_W * 0.78,
    gap: 11,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.2,
        shadowRadius: 16,
      },
      android: { elevation: 10 },
    }),
  },
  daySun: { fontSize: 52 },
  dayTitle: { fontSize: 22, fontFamily: FF, color: P.green1 },
  dayStat: { fontSize: 15, fontFamily: FF, color: "#374151" },
  dayHint: {
    fontSize: 11,
    fontFamily: FF,
    color: "#9CA3AF",
    textAlign: "center",
  },
  dayBtn: {
    marginTop: 8,
    backgroundColor: P.green2,
    paddingHorizontal: 26,
    paddingVertical: 13,
    borderRadius: 13,
  },
  dayBtnTxt: { color: P.white, fontFamily: FF, fontSize: 15 },
});
